name: release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Python 3.9
      run: uv python install 3.9

    - name: Build package
      run: uv build

    - uses: actions/upload-artifact@v5
      with:
        name: dist
        path: dist

  release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:

    - name: Download a distribution artifact
      uses: actions/download-artifact@v5
      with:
        name: dist
        path: dist

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
